# Generated by Django 3.2.7 on 2022-09-02 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('documentId', models.AutoField(primary_key=True, serialize=False)),
                ('documentName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.BigIntegerField()),
                ('names', models.CharField(max_length=60)),
                ('surnames', models.CharField(max_length=60)),
                ('hobbie', models.CharField(max_length=150)),
                ('Tipe_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
        ),
    ]
